version: '3.1'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "while :; do echo '.'; sleep 5 ; done"
   # container_name: first_project
   # volumes:
   # - .:/first_project
    ports:
      - 8000:8000
