kind: Service
apiVersion: v1
metadata:
  #Service name
  name: flickr-app-svc
spec:
  selector:
    app: myfirstproject-239707
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer