# Generated by Django 2.2 on 2019-04-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0002_imagesandtags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagesAndTags',
        ),
    ]
