# Generated by Django 2.2 on 2019-04-28 23:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0003_delete_imagesandtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='imageFile',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/thanika/Spring 2019/Big Data Architecture/Django/first_project/imageApp/searchUploads'), upload_to=''),
        ),
    ]
