# Generated by Django 2.2 on 2019-04-29 00:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0004_auto_20190428_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='imageFile',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/thanika/Spring 2019/Big Data Architecture/Django/first_project/imageApp/static/imageApp/searchUploads'), upload_to=''),
        ),
    ]
