# Generated by Django 2.2 on 2019-05-01 23:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0005_auto_20190429_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/thanika/Spring 2019/Big Data Architecture/Django/first_project/imageApp/static/imageApp/uploads'), upload_to='')),
            ],
        ),
    ]
